### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dfdfdfs** [LXGaming/Reconstruct#6]
-mapping <ProGuard mappings>

And if there is no map file? Then don't deobfuscate?
It's just that developers usually don't upload a map file next to an obfuscated file.

**Comment by LXGaming** [comment]
This application is specifically for reversing the various renames done by obfuscation, It requires the map file.

There are alternative applications such as [java-deobfuscator/deobfuscator](https://github.com/java-deobfuscator/deobfuscator) which are more suited for deobfuscation in the cases where you do not have the map file.

**Comment by dfdfdfs** [comment]
I've tried these alternative deobfuscators. They don't work. Or can you recommend a string deobfuscator for ProGuard?

**Comment by LXGaming** [comment]
No sorry, The one I linked before is the only the I know of.

**Comment by dfdfdfs** [comment]
Ok.
