### ISSUE TITLE
Quiet mode

### ISSUE THREAD

**Issue by DelofJ** [LXGaming/Reconstruct#8]
If you want to use this tool in a script, it will ask for the user to "Press Enter to continue", and so it is not really usable in an automated script
Is there a way to disable this by doing a "-q", "-quiet" or "--quiet" ?

**Comment by LXGaming** [comment]
Use `-agree` or `--agree` https://github.com/LXGaming/Reconstruct/blob/aae0d0ca239699a21514457409700ef05f3dab43/cli/src/main/java/io/github/lxgaming/reconstruct/cli/configuration/ConfigImpl.java#L52-L53

**Comment by LXGaming** [comment]
I'm assuming this is resolved, If it's still an issue please let me know.

**Comment by DelofJ** [comment]
Well I didn't know there was this argument, thanks
